apiVersion: v1
kind: Service
metadata:
  name: requests-np
spec:
  type: NodePort
  selector:
    app: requestsservice
  ports:
    - name: requestsservice
      protocol: TCP
      port: 80
      targetPort: 80
