apiVersion: v1
kind: Service
metadata:
  name: users-np
spec:
  type: NodePort
  selector:
    app: usersservice
  ports:
    - name: usersservice
      protocol: TCP
      port: 80
      targetPort: 80
